### ISSUE TITLE
Access to guide tour

### ISSUE THREAD

**Issue by spreekaiser** [spreekaiser/schifffahrten.berlin#1]
## Value proposition

As an User
I want scann a QR code and get access to the guide tour
So that I can hear informations about what I see during the boot trip

## Description

- After scanning a QR code, the user is taken to a guide portal
- Nutzer kann seine gewünschte Sprache auswählen
- If it matches the stored GPS points, an audio is played

## Acceptance criteria

- [ ] User listens to the stored audio in the defined GPS point

## Tasks

- [ ] get the GPS data
- [ ] if GPS is right play audio for informations
- [ ] if GPS is wrong say that they can bay a ticket

**Comment by mntzd** [comment]
Also: Where do they scan the QR code? :)

**Comment by spreekaiser** [comment]
create QR code for this link
