### ISSUE TITLE
Show single trip offer

### ISSUE THREAD

**Issue by spreekaiser** [spreekaiser/schifffahrten.berlin#3]

**Comment by spreekaiser** [comment]
## Value proposition

As an User
I want to see all the information about an offered boat trip
So that I can choose to buy a ticket

## Description

- In a window are listet all informations of an offered boat trip
- There is a button to buy the trip
- There is a button to go back to the list

## Acceptance criteria

- [ ] When all informations are listet in a readable way
- [ ] When the buy-button is working
- [ ] When the go-back-button is working

## Tasks

- [ ] create a window to show all informations about a single offered trip
- [ ] add a button to buy this trip
- [ ] add a button to go back to list
