### ISSUE TITLE
Filtered List of boat trips

### ISSUE THREAD

**Issue by spreekaiser** [spreekaiser/schifffahrten.berlin#8]
## Value proposition

As an User
I want to filter the list of offered boat trips
So that I can specify my search if I like

## Description

- The search can filtered by the rivers Spree, Havel, Dahme and the Channels
- The search can filtered by the duration time of the boat trip

## Acceptance criteria

- [ ] Can I filter the list of boat trips for each river?
- [ ] Can I filter the list of boat trips by the duration time?
- [ ] Can I go back to the list of all offered boat trips?

## Tasks

- [ ] Filter the list for each river by key
- [ ] Filter the list by duration time by key
- [ ] Add button to unfiltered and got back to list of all offered trips
